### PR TITLE
Update of ada.html

### PR DESCRIPTION
**Pull request by DirkCraeynest**
Revised and updated the intro text for the Ada Developer Room.

### CODE REVIEW

**Comment by gerryd** [comment]
Merged, thanks!

**Comment by DirkCraeynest** [comment]
Thanks for merging.

However, on https://fosdem.org/2018/schedule/track/ada/ I still see
the old version of the intro text.  Is something more needed?

Dirk Craeynest
Ada DevRoom


= Date: Sun, 07 Jan 2018 15:26:56 +0000 (UTC)
= From: Gerry Demaret <notifications@github.com>
= Reply-To: FOSDEM/website <reply@reply.github.com>
= To: FOSDEM/website <website@noreply.github.com>
= cc: DirkCraeynest <Dirk.Craeynest@cs.kuleuven.be>, 
=         Author <author@noreply.github.com>
= Subject: Re: [FOSDEM/website] Update of ada.html (#39)
= 
= Merged, thanks!
= 
= -- 
= You are receiving this because you authored the thread.
= Reply to this email directly or view it on GitHub:
= https://github.com/FOSDEM/website/pull/39#issuecomment-355830284

**Comment by gerryd** [comment]
Right, seems the file wasn't in the correct location. Fixed in a056a96b2e40cf56c2c897ba96835b1da4267b59. Should be there now.

**Comment by DirkCraeynest** [comment]
= Right, seems the file wasn't in the correct location. Fixed in
= a056a96b2e40cf56c2c897ba96835b1da4267b59. Should be there now.

The Ada DevRoom intro on the web site has indeed been updated now.
Thanks!

**Pull request merged**
