### PR TITLE
Adds Docker support and notes on how to leverage it in the README

### PR DESCRIPTION
**Pull request by spikeheap**
This PR adds the ability to run the site generator in a Docker container. This can be particularly handy to isolate dependencies (e.g. if you don't have ruby 2.1.5 or a version manager installed already).

Running it within Docker isn't mandatory, and does slow down the build, but may be useful for testing upgrades and so forth.

### CODE REVIEW

**Comment by spikeheap** [comment]
It doesn't look like this change is wanted, so I'll close this PR

**Comment by Ryuno-Ki** [comment]
Thank you for putting together this nevertheless, @spikeheap.
During FOSDEM today, there was some openness towards feedback & improvements on the website.
Looking at the current installation steps, I was scared to mess up my machine.
So even if it is not becoming a part of the website itself, knowing how to set up a local Docker image could allow me to provide improvements on the UI.

**Comment by johanvdw** [comment]
I did a brief check (after updating docker to ruby 2.2).
I was not able to connect to the fosdem postgresql (using kerberos) to update, which is quite logical.

Anyway, the current way is also not very handy for people outside the fosdem core team. I will check if we can not provide the pentabarf.yaml file somewhere.

Ryuno-Ki: I have used the install instructions, but rather than adding stuff to my .bashrc I created a file start_fosdem_ruby.sh containing these steps. If you then do source start_fosdem_ruby.sh you have a fosdem environment only active when working on the website. I also like that more than screwing up my .bashrc.

**Comment by gerryd** [comment]
> Anyway, the current way is also not very handy for people outside the fosdem core team. I will check if we can not provide the pentabarf.yaml file somewhere.

Perhaps including a pentabarf.yaml with one sample room, one sample talk and one sample speaker or some such would be a good start?

**Comment by Ryuno-Ki** [comment]
> Ryuno-Ki: I have used the install instructions, but rather than adding stuff to my .bashrc I created a file start_fosdem_ruby.sh containing these steps. If you then do source start_fosdem_ruby.sh you have a fosdem environment only active when working on the website. I also like that more than screwing up my .bashrc.

Will let you know once I tried it myself.

**Comment by gerryd** [comment]
> > Anyway, the current way is also not very handy for people outside the fosdem core team. I will check if we can not provide the pentabarf.yaml file somewhere.
> 
> Perhaps including a pentabarf.yaml with one sample room, one sample talk and one sample speaker or some such would be a good start?

Put my foot where my mouth is, so as of 9ff162f there's now sample data in the `sample/` folder, and the README explains how to move it in place.

**Comment by johanvdw** [comment]
I have tested this and merged conflicts in the README.md. I pushed to the branch, but it seems github has not picked that up yet (first time I encounter this). I think having a docker method is definitely good, we could probably reuse this if we add ci to this repo.

**Pull request merged**
