### PR TITLE
Make the website responsive

### PR DESCRIPTION
**Pull request by maeligg**
Hello,

This PR aims to make the Fosdem website responsive. I limited the refactoring to what I consider the minimum to make the website look "OK" on mobile and intentionally didn't make any big design changes (although it could probably use some).
fosdem-responsive
I don't know the website that well so it would be helpful if someone who does could check out the branch and verify that I didn't forget or break any layouts.

Cheers

### CODE REVIEW

**Comment by gerryd** [comment]
Hi Maël,

Thank you for the improvements you made! It looks rather good to me. I've pinged the others on the website team to have a look, I hope they will leave some feedback as well.

Cheers!

**Comment by Mixone-FinallyHere** [comment]
Looks good to me as well.

The code changes seem to be similar to what I was thinking about, I just didn't have time to implement it (finally got a job so been busy).

I'll pull and test at home this weekend on a couple of emulated devices

Miguel

**Comment by emanuil-tolev** [comment]
Re testing, if it doesn't break the desktop version (doesn't seem to), go ahead. Atm we do very close to nothing for a responsive layout so anything is an improvement.

**Comment by RichiH** [comment]
Didn't check the code, but the animated gif looks good as to responsiveness.

**Comment by gerryd** [comment]
Everyone seemed happy with the changes, so I've gone ahead and merged them.

Thanks, Maël!

**Pull request merged**
