### PR TITLE
CfP for HPC, Big Data, and Data Science devroom

### PR DESCRIPTION
**Pull request by boegel**
cc @mxm, @vasia, @rvs

### CODE REVIEW

**Comment by johanvdw** [comment]
On the bottom of your page you have: hpc-bigdata-devroom@lists.fosdem.org

**Comment by boegel** [comment]
@johanvdw Can you clarify why that's an issue? It should be  hpc-bigdata-devroom@fosdem.org instead?

We've always used  hpc-bigdata-devroom@lists.fosdem.org in the past, which has worked fine, but maybe something changed...

**Comment by johanvdw** [comment]
Kenneth, I sent a testmail to the address. If it arrived - all ok.

Most devrooms area aliases, just wanted to check to be sure.

**Comment by boegel** [comment]
It did arrive indeed (I replied to it), so OK, we'll leave it as is

**Pull request merged**
