### PR TITLE
Add extra tags and attributes to Pentabarf XML schedule file

### PR DESCRIPTION
**Pull request by cbeyls**
The goal of these changes is to be compliant with the FRAB and Pretalx file formats, which are an evolution of the original Pentabarf XML file format.

All existing tags and attributes are preserved to ensure backwards compatibility.

The following tags and attributes have been added to be compliant with the new file formats:
- `schedule/version`:  the newly exported schedule version (tag must be present).
- `schedule/conference/acronym`: identifier for the conference, must be lower case to comply with the format.
- `schedule/conference/base_url`
- `schedule/conference/time_zone_name`: this tag is already present in `pentabarf-tz.xml`
- `schedule/day[start]` and `schedule/day[end]`: start and end time of day according to the value of `day_change`, in ISO8601 format (includes the UTC offset). Since the UTC offset is not present in the days dataset, the date is combined with the TimeZone information provided by the TzInfo library.
- `schedule/day/room/event[guid]`: the newly exported event guid.
- `schedule/day/room/event/date`: the start time of the event, in ISO8601 format (includes the UTC offset).
- `schedule/day/room/event/url`: the web URL of the event details on the FOSDEM website.

> Note that after applying these changes, the file will still not comply with the [c3conf XSD validator](https://c3voc.de/schedulexml/) because it considers any unknown tag or attribute as an error. However, lenient XML parsers that simply ignore unknown tags and attributes will be able to read the file without errors.

In addition, the following attribute has also been added:
- `schedule/day/room[slug]`: the slug is the unique identifier of a room across the different applications and APIs used by FOSDEM. Providing this value is thus very useful to apps.

In a future pull request, we could also consider adding speaker information to a new root tag.

### CODE REVIEW

**Comment by johanvdw** [comment]
Thanks for your work!

Some comments:
* We already have a xml-tz variant. If we add timezones here we should probably get rid of that;
* It is important to keep in mind that our source database is now pretalx. Pretalx also generates an xml, so we should probably try to either align to that, or consider dropping generating another xml in the website build if the pretalx xml is better already. In particular I think that we should not add uuid's here but rather reuse the ones that pretalx generates and stores. I can add them to the yaml export that the website build uses.

**Comment by cbeyls** [comment]
> Thanks for your work!
> 
> Some comments:
> 
>     * We already have a xml-tz variant. If we add timezones here we should probably get rid of that;
> 
Okay, I'll update the pull request to remove the other file.

>     * It is important to keep in mind that our source database is now pretalx. Pretalx also generates an xml, so we should probably try to either align to that, or consider dropping generating another xml in the website build if the pretalx xml is better already. In particular I think that we should not add uuid's here but rather reuse the ones that pretalx generates and stores. I can add them to the yaml export that the website build uses.

I fully agree; this implementation was made to work with the existing export file format but if you can add more fields to the source pentabarf.yaml it would simplify the code and ensure that we get the same values as in the file generated by Pretalx. Mainly the event guid and the day start and end time.

The code that generates the event URL is a quick hack that could break if the site structure or configuration changes so if you know a better way to get a routing URL from nanoc feel free to share it.

The important thing is that you now have a clear view of what fields should be added.

**Comment by johanvdw** [comment]
I added schedule_version and event guid (https://github.com/FOSDEM/pretalx-integration/commit/71002d6e2cf7e5b1d19abcd915e6e027c08eb1ac), you may want to test with

https://github.com/FOSDEM/website/blob/master/config.yaml#L176-L179
hos:t https://pretalx-test.fosdem.org
conference_slug: democon
(which would generate)
https://pretalx-test.fosdem.org/democon/schedule/export/NanocExporter

Note that if you would like access to this test instance for tests we can provide that.

**Comment by cbeyls** [comment]
> I added schedule_version and event guid ([FOSDEM/pretalx-integration@71002d6](https://github.com/FOSDEM/pretalx-integration/commit/71002d6e2cf7e5b1d19abcd915e6e027c08eb1ac)), you may want to test with
> 
> https://github.com/FOSDEM/website/blob/master/config.yaml#L176-L179 hos:t https://pretalx-test.fosdem.org conference_slug: democon (which would generate) https://pretalx-test.fosdem.org/democon/schedule/export/NanocExporter
> 
> Note that if you would like access to this test instance for tests we can provide that.

I'm not ready to setup everything to export from Pretalx on my machine. If you can provide me a test pentabarf.yaml export file, I can test if the XML is correct. Ideally, the sample file in this repo should be updated to include the new fields.

**Comment by johanvdw** [comment]
So I propose to merge this now so app developers have enough time to adjust if needed, and otherwise this will be lying around for anouther year.

**Comment by cbeyls** [comment]
I saw you reverted the merge. Did you find an issue in the code?

**Comment by johanvdw** [comment]
So I swear I put a comment here, but it somehow disappeared.

There was an issue -> the website didn't build anymore. I reverted so we can have a closer look. Likely it's something easy, but I wanted to make sure the build would still work before looking in more detail.

**Comment by johanvdw** [comment]
```
johan@x1:~/git/fosdem/website((HEAD detached from cbeyls))$  nanoc
Loading site data… done
Compiling site…

Captain! We’ve been hit!

Message:

ArgumentError: invalid date: "2024-02-03T00:00"

Compilation stack:

  - [item]   /schedule/pentabarf/ (rep default)

Stack trace:

  0. /home/johan/.rbenv/versions/2.7.0/lib/ruby/2.7.0/time.rb:639:in `xmlschema'
  1. item /schedule/pentabarf/ (rep default):36:in `block (2 levels) in get_binding'
  2. item /schedule/pentabarf/ (rep default):35:in `each'
  3. item /schedule/pentabarf/ (rep default):35:in `each_with_index'
  4. item /schedule/pentabarf/ (rep default):35:in `block in get_binding'
  5. /home/johan/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
  6. /home/johan/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
  7. /home/johan/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:94:in `method_missing'
  8. item /schedule/pentabarf/ (rep default):13:in `get_binding'
  9. /home/johan/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:905:in `eval'
  ... 35 more lines omitted. See full crash log for details.

If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.

```

**Comment by johanvdw** [comment]
This is the export I used. You may have to cherry-pick the last change of the repo to get to this point.

[export.tar.gz](https://github.com/FOSDEM/website/files/13646374/export.tar.gz)

**Comment by cbeyls** [comment]
Thank you, I'll take a look at the export file when I have time.
Most likely date formats have changed in the export file compared to the the sample file, which is what I used to test the code.

**Comment by cbeyls** [comment]
What's the policy in case of an inconsistency between the export file and the sample file? Should we update the sample file and site generator to align with the new format, or should we change the exporter to comply with the previous date format?

**Comment by cbeyls** [comment]
@johanvdw I found the issue.

In the sample export file:

`day_change: '00:00:00'`

In the production export file:

`day_change: '00:00'`

The **day_change** field is missing seconds. It should probably be fixed in the exporter code.

If you update the exporter, you may consider adding the Markdown to HTML conversion upstream, so we don't have to convert Markdown to HTML both on the site pages and for the schedule XML file.

**Comment by cbeyls** [comment]
I found another issue in the export file, leading to inconsistent data in the XML file compared to last year's file format.

In each `<event>`, the fields `room` and `room_name` contain the same value (the slug), and in the XML schedule file the field `room` (the slug) is used, while it should be `room_name` (the name) because it needs to match the value of the attribute `name` in the parent `<room>` tag.

2023 XML schedule format (valid):

```
    <room name="K.4.201">
      <event id="13779">
        <room>K.4.201</room>
```

2024 current XML schedule format (invalid):

```
    <room name="K.4.201">
      <event id="5132">
        <room>k4201</room>
```

Expected 2024 XML schedule format after fixes:

```
    <room name="K.4.201" slug="k4201">
      <event id="5132">
        <room>K.4.201</room>
```

**Comment by johanvdw** [comment]
I applied your changes, but still get errors when reapplying your branch

**Comment by johanvdw** [comment]
Also for your info, I originally did some quite dirty stuff to get a yaml with dates and time differences in a format that nanoc wanted.

https://github.com/FOSDEM/pretalx-integration/blob/master/devroom-settings/devroom_settings/nanoc.py#L520-L527

Ideally we could get rid of that as well. Anyway, if I manually edit the yaml to make sure that 00:00:00 is quoted is I get:
`Loading site data… done
Compiling site…

Captain! We’ve been hit!

Message:

ArgumentError: invalid date or strptime format - `2024-02-03 10:30:00+01:00' `%Y-%m-%d %H:%M:%S.%N %z'

Compilation stack:

  - [item]   /schedule/pentabarf/ (rep default)

Stack trace:
`

**Comment by cbeyls** [comment]
It's a similar issue.

In the sample export file:

`start_datetime: '2021-02-06 10:50:00.000000000 +0100'`

In the production export file:

`start_datetime: '2024-02-03 10:30:00+01:00'`

There is no nanosecond part and the timezone is attached to the time.

Should I make a new pull request that follows the current specs of the export file and update the sample export file to follow that new format? Or do yo want to change the export file format to comply with the sample file?

**Comment by cbeyls** [comment]
I noticed this today.

2023 XML schedule format (valid):
```
<schedule>
    <conference>
        <day_change>09:00:00</day_change>
```

2024 current XML schedule format (invalid):
```
<schedule>
    <conference>
        <day_change>0</day_change>
```

I'm afraid some parsers will fail trying to interpret the time of the day change.

**Comment by johanvdw** [comment]
> I found another issue in the export file, leading to inconsistent data in the XML file compared to last year's file format.
> 
> In each exported event, the fields `room` and `room_name` contain the same value (the slug), and in the XML schedule file the field `room` (the slug) is used, while it should be `room_name` (the name) because it needs to match the value of the attribute `name` in the parent `<room>` tag.
> 
> 2023 XML schedule format (valid):
> 
> ```
>     <room name="K.4.201">
>       <event id="13779">
>         <room>K.4.201</room>
> ```
> 
> 2024 current XML schedule format (invalid):
> 
> ```
>     <room name="K.4.201">
>       <event id="5132">
>         <room>k4201</room>
> ```
> 
> Expected 2024 XML schedule format after fixes:
> 
> ```
>     <room name="K.4.201" slug="k4201">
>       <event id="5132">
>         <room>K.4.201</room>
> ```

This was adjusted

**Comment by johanvdw** [comment]
> It's a similar issue.
> 
> In the sample export file:
> 
> `start_datetime: '2021-02-06 10:50:00.000000000 +0100'`
> 
> In the production export file:
> 
> `start_datetime: '2024-02-03 10:30:00+01:00'`
> 
> There is no nanosecond part and the timezone is attached to the time.
> 
> Should I make a new pull request that follows the current specs of the export file and update the sample export file to follow that new format? Or do you want to change the export file format to comply with the sample file?

Nanosecond precision seems a bit overkill for a conference, so I'll try fixing that in the export.

**Comment by cbeyls** [comment]
I saw you fixed the Markdown conversion to HTML upstream as well.

Do you have the latest export file for reference so I can create another pull request matching that format?

**Comment by johanvdw** [comment]
This is the file. Note I'm still struggling with a remaining website issue https://github.com/FOSDEM/pretalx-integration/issues/41 - so something may still change.

In any case if you spot anything that could be related, let me know :-)
last export:
[export.tar.gz](https://github.com/FOSDEM/website/files/13731472/export.tar.gz)

I've not yet touched the datetime format.

**Comment by johnjohndoe** [comment]
@johanvdw & @cbeyls Thank you for going through all of this!!!

**Pull request merged**
